ALTER TABLE "Book" ADD COLUMN "usageInputTokens" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Book" ADD COLUMN "usageOutputTokens" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Book" ADD COLUMN "usageByStage" JSONB NOT NULL DEFAULT '{}';
